// frontend/src/App.jsx
import { useEffect, useMemo, useRef, useState } from "react";
import { apiRequest, loadPanelConfig } from "./api";
import LoginScreen from "./components/LoginScreen";
import Sidebar from "./components/Sidebar";
import ProcessesView from "./components/ProcessesView";
import LogsView from "./components/LogsView";
import PerformanceView from "./components/PerformanceView";
import CommandDialog from "./components/CommandDialog";

const PASSWORD_KEY = "cmdhub-panel-password";

function formatBytes(bytes) {
  if (typeof bytes !== "number" || !Number.isFinite(bytes)) return "-";
  const kb = 1024;
  const mb = 1024 * kb;
  const gb = 1024 * mb;
  if (bytes >= gb) return `${(bytes / gb).toFixed(2)} GB`;
  if (bytes >= mb) return `${(bytes / mb).toFixed(2)} MB`;
  if (bytes >= kb) return `${(bytes / kb).toFixed(2)} KB`;
  return `${bytes} B`;
}

export default function App() {
  const [apiPort, setApiPort] = useState(null);
  const [panelPort, setPanelPort] = useState(null);
  const [password, setPassword] = useState("");
  const [authError, setAuthError] = useState("");
  const [authBusy, setAuthBusy] = useState(false);
  const [authed, setAuthed] = useState(false);
  const [tab, setTab] = useState("processes");
  const [processes, setProcesses] = useState([]);
  const [toast, setToast] = useState("");
  const [logsText, setLogsText] = useState("");
  const [logsTail, setLogsTail] = useState(16000);
  const [logsAutoRefresh, setLogsAutoRefresh] = useState(true);
  const [selectedLogsId, setSelectedLogsId] = useState(null);
  const [selectedPerfId, setSelectedPerfId] = useState(null);
  const [cpuPoints, setCpuPoints] = useState([]);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [dialogProcess, setDialogProcess] = useState(null);

  // Refs to avoid stale closures in the process-refresh interval
  const selectedLogsIdRef = useRef(selectedLogsId);
  const selectedPerfIdRef = useRef(selectedPerfId);
  selectedLogsIdRef.current = selectedLogsId;
  selectedPerfIdRef.current = selectedPerfId;

  const apiBase = useMemo(() => {
    if (!apiPort) return "";
    return `${window.location.protocol}//${window.location.hostname}:${apiPort}/api`;
  }, [apiPort]);

  const selectedPerf = useMemo(() => {
    const process = processes.find((item) => item.id === selectedPerfId);
    if (!process) return null;
    return {
      ...process,
      workingSetDisplay: formatBytes(process.workingSetBytes),
      privateMemoryDisplay: formatBytes(process.privateMemoryBytes)
    };
  }, [processes, selectedPerfId]);

  useEffect(() => {
    loadPanelConfig()
      .then((config) => {
        setApiPort(config.apiPort);
        setPanelPort(config.panelPort ?? null);
      })
      .catch((error) => {
        setAuthError(error.message);
      });
  }, []);

  useEffect(() => {
    if (!apiBase) return;
    const remembered = localStorage.getItem(PASSWORD_KEY);
    if (remembered) {
      void login(remembered, true);
    }
  }, [apiBase]);

  useEffect(() => {
    if (!authed || !apiBase) return;
    void refreshProcesses();
    const timer = window.setInterval(() => {
      void refreshProcesses();
    }, 2000);
    return () => window.clearInterval(timer);
  }, [authed, apiBase]);

  useEffect(() => {
    if (!authed || !apiBase || tab !== "logs" || !selectedLogsId || !logsAutoRefresh) return;
    void refreshLogs();
    const timer = window.setInterval(() => {
      void refreshLogs();
    }, 1600);
    return () => window.clearInterval(timer);
  }, [authed, apiBase, tab, selectedLogsId, logsTail, logsAutoRefresh]);

  useEffect(() => {
    if (!selectedPerf) return;
    setCpuPoints((prev) => {
      const next = [...prev, selectedPerf.cpuPercent ?? 0];
      return next.slice(-60);
    });
  }, [selectedPerf?.cpuPercent]);

  useEffect(() => {
    if (!toast) return;
    const timer = window.setTimeout(() => setToast(""), 2200);
    return () => window.clearTimeout(timer);
  }, [toast]);

  async function login(value, remember) {
    if (!apiBase) return;
    setAuthBusy(true);
    setAuthError("");

    try {
      await apiRequest(apiBase, value, "/processes");
      setPassword(value);
      setAuthed(true);
      if (remember) {
        localStorage.setItem(PASSWORD_KEY, value);
      } else {
        localStorage.removeItem(PASSWORD_KEY);
      }
    } catch (error) {
      setAuthed(false);
      setAuthError(error.message || "Authentication failed.");
    } finally {
      setAuthBusy(false);
    }
  }

  function logout() {
    setAuthed(false);
    setPassword("");
    localStorage.removeItem(PASSWORD_KEY);
  }

  async function refreshProcesses() {
    if (!authed || !apiBase) return;
    const response = await apiRequest(apiBase, password, "/processes");
    const list = response?.processes || [];
    setProcesses(list);

    if (!selectedLogsIdRef.current && list.length) {
      setSelectedLogsId(list[0].id);
    }

    if (!selectedPerfIdRef.current && list.length) {
      setSelectedPerfId(list[0].id);
    }
  }

  async function refreshLogs() {
    if (!selectedLogsId || !authed || !apiBase) return;
    const response = await apiRequest(apiBase, password, `/processes/${encodeURIComponent(selectedLogsId)}/logs?tail=${logsTail}`);
    const text = (response?.logs || []).join("\n");
    setLogsText(text);
  }

  async function commandAction(id, action) {
    await apiRequest(apiBase, password, `/processes/${encodeURIComponent(id)}/actions/${action}`, { method: "POST" });
    setToast(`Action ${action} requested.`);
    await refreshProcesses();
  }

  async function clearLogs() {
    if (!selectedLogsId) return;
    await commandAction(selectedLogsId, "clear-logs");
    setLogsText("");
  }

  async function removeProcess(id) {
    if (!window.confirm("Delete this command?")) {
      return;
    }

    await apiRequest(apiBase, password, `/processes/${encodeURIComponent(id)}`, { method: "DELETE" });
    setToast("Command deleted.");
    await refreshProcesses();
  }

  async function saveCommand(model) {
    const payload = {
      ...model,
      runEveryUnit: "minutes",
      restartEveryUnit: "minutes"
    };

    if (dialogProcess) {
      await apiRequest(apiBase, password, `/processes/${encodeURIComponent(dialogProcess.id)}`, {
        method: "PUT",
        body: JSON.stringify(payload)
      });
      setToast("Command updated.");
    } else {
      await apiRequest(apiBase, password, "/processes", {
        method: "POST",
        body: JSON.stringify(payload)
      });
      setToast("Command created.");
    }

    setDialogOpen(false);
    setDialogProcess(null);
    await refreshProcesses();
  }

  if (!authed) {
    return <LoginScreen onLogin={login} loading={authBusy} error={authError} />;
  }

  return (
    <div className="app-layout">
      <Sidebar
        activeTab={tab}
        onTabChange={setTab}
        apiPort={apiPort}
        panelPort={panelPort}
        onSettings={() => setToast("Settings are managed in the desktop app.")}
        onLogout={logout}
      />

      <main className="main-content">
        {tab === "processes" ? (
          <ProcessesView
            processes={processes}
            onCreate={() => {
              setDialogProcess(null);
              setDialogOpen(true);
            }}
            onRefresh={refreshProcesses}
            onEdit={(process) => {
              setDialogProcess(process);
              setDialogOpen(true);
            }}
            onAction={commandAction}
            onDelete={removeProcess}
            onOpenLogs={(id) => {
              setSelectedLogsId(id);
              setTab("logs");
            }}
            onOpenPerformance={(id) => {
              setSelectedPerfId(id);
              setCpuPoints([]);
              setTab("performance");
            }}
          />
        ) : null}

        {tab === "logs" ? (
          <LogsView
            processes={processes}
            selectedId={selectedLogsId}
            logs={logsText}
            tail={logsTail}
            autoRefresh={logsAutoRefresh}
            onSelect={(id) => {
              setSelectedLogsId(id);
              setLogsText("");
            }}
            onTailChange={setLogsTail}
            onAutoRefreshChange={setLogsAutoRefresh}
            onRefresh={refreshLogs}
            onClear={clearLogs}
          />
        ) : null}

        {tab === "performance" ? (
          <PerformanceView
            processes={processes}
            selected={selectedPerf}
            selectedId={selectedPerfId}
            cpuHistory={{ points: cpuPoints, available: processes }}
            onSelect={(id) => {
              setSelectedPerfId(id);
              setCpuPoints([]);
            }}
          />
        ) : null}

        <CommandDialog
          process={dialogProcess}
          open={dialogOpen}
          onClose={() => {
            setDialogOpen(false);
            setDialogProcess(null);
          }}
          onSave={saveCommand}
        />

        {toast ? <div className="toast">{toast}</div> : null}
      </main>
    </div>
  );
}

// nuxt-new/app.vue
<template>
  <div>
    <LoginScreen
      v-if="!authed"
      :loading="authBusy"
      :error="authError"
      @login="onLogin"
    />

    <div v-else class="app-layout">
      <AppSidebar
        :active-tab="activeTab"
        :api-port="apiPort"
        :panel-port="panelPort"
        @tab-change="activeTab = $event"
        @settings="toast = 'Settings are managed in the desktop app.'"
        @logout="onLogout"
      />

      <main class="main-content">
        <ProcessesView
          v-if="activeTab === 'processes'"
          :processes="processes"
          @create="openCreateDialog"
          @refresh="refreshProcesses"
          @edit="openEditDialog"
          @action="onAction"
          @delete="onDelete"
          @open-logs="onOpenLogs"
          @open-performance="onOpenPerformance"
        />

        <LogsView
          v-if="activeTab === 'logs'"
          :processes="processes"
          :selected-id="selectedLogsId"
          :logs="logsText"
          :tail="logsTail"
          :auto-refresh="logsAutoRefresh"
          @select="selectLogsProcess"
          @tail-change="logsTail = $event"
          @auto-refresh-change="logsAutoRefresh = $event"
          @refresh="refreshLogs"
          @clear="clearLogs"
        />

        <PerformanceView
          v-if="activeTab === 'performance'"
          :processes="processes"
          :selected="selectedPerf"
          :selected-id="selectedPerfId"
          :cpu-points="cpuPoints"
          @select="selectPerfProcess"
        />

        <CommandDialog
          :process="dialogProcess"
          :open="dialogOpen"
          @close="closeDialog"
          @save="onSave"
        />

        <ToastNotification :message="toast" />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Process, CommandForm, TabId } from '~/types'

const { apiPort, panelPort, password, authed, authError, authBusy, apiBase, init, login, logout, tryRemembered } = useAuth()
const { processes, refreshProcesses, commandAction, removeProcess, saveCommand } = useProcesses(apiBase, password)
const { logsText, logsTail, logsAutoRefresh, selectedLogsId, refreshLogs, clearLogs, selectProcess: selectLogsProcess } = useLogs(apiBase, password)
const { selectedPerfId, cpuPoints, selectedPerf, selectProcess: selectPerfProcess } = usePerformance(processes)

const activeTab = ref<TabId>('processes')
const dialogOpen = ref(false)
const dialogProcess = ref<Process | null>(null)
const toast = ref('')

let processTimer: ReturnType<typeof setInterval> | null = null
let logsTimer: ReturnType<typeof setInterval> | null = null

onMounted(async () => {
  await init()
  tryRemembered()
})

watch(authed, (val) => {
  if (val && apiBase.value) {
    startPolling()
  } else {
    stopPolling()
  }
})

watch([activeTab, selectedLogsId, logsTail, logsAutoRefresh], () => {
  if (logsTimer) clearInterval(logsTimer)
  if (authed.value && activeTab.value === 'logs' && selectedLogsId.value && logsAutoRefresh.value) {
    refreshLogs()
    logsTimer = setInterval(refreshLogs, 1600)
  }
})

function startPolling() {
  refreshProcesses()
  processTimer = setInterval(refreshProcesses, 2000)
}

function stopPolling() {
  if (processTimer) clearInterval(processTimer)
  if (logsTimer) clearInterval(logsTimer)
}

watch(processes, (list) => {
  if (!selectedLogsId.value && list.length) selectedLogsId.value = list[0].id
  if (!selectedPerfId.value && list.length) selectPerfProcess(list[0].id)
})

watch(toast, (val) => {
  if (!val) return
  setTimeout(() => { toast.value = '' }, 2200)
})

async function onLogin(value: string, remember: boolean) {
  await login(value, remember)
}

function onLogout() {
  stopPolling()
  logout()
}

async function onAction(id: string, action: string) {
  await commandAction(id, action)
  toast.value = `Action ${action} requested.`
}

async function onDelete(id: string) {
  if (!confirm('Delete this command?')) return
  await removeProcess(id)
  toast.value = 'Command deleted.'
}

function openCreateDialog() {
  dialogProcess.value = null
  dialogOpen.value = true
}

function openEditDialog(process: Process) {
  dialogProcess.value = process
  dialogOpen.value = true
}

function closeDialog() {
  dialogOpen.value = false
  dialogProcess.value = null
}

async function onSave(model: CommandForm) {
  await saveCommand(model, dialogProcess.value?.id)
  toast.value = dialogProcess.value ? 'Command updated.' : 'Command created.'
  closeDialog()
}

function onOpenLogs(id: string) {
  selectLogsProcess(id)
  activeTab.value = 'logs'
}

function onOpenPerformance(id: string) {
  selectPerfProcess(id)
  activeTab.value = 'performance'
}

onUnmounted(stopPolling)
</script>
